GET http://localhost:8080/api/users

###

POST http://localhost:8080/api/users
Content-Type: application/json

{
    "first_name": "Amauri",
    "last_name": "Blanco",
    "biography": "Teste"
}

###

GET http://localhost:8080/api/users/7fb5a2bf-33bf-4da9-b73a-31052db659c6

###

DELETE http://localhost:8080/api/users/d51d3363-4c32-40cc-b4f7-e467c1c668bb

###

PUT http://localhost:8080/api/users/d9c75fcc-a0e0-4fee-a4df-e409b893ef5c
Content-Type: application/json

{
    "first_name": "Elton",
    "last_name": "Blanco",
    "biography": "Updated"
}