GET http://localhost:8080/api/users

###

POST http://localhost:8080/api/users
Content-Type: application/json

{
    "first_name": "Amauri",
    "last_name": "Blanco",
    "biography": "Teste"
}

###

GET http://localhost:8080/api/users/d32c019c-710a-4535-8736-07fc0a48a549

###

DELETE http://localhost:8080/api/users/d51d3363-4c32-40cc-b4f7-e467c1c668bb