GET http://localhost:8080/api/users

###

POST http://localhost:8080/api/users
Content-Type: application/json

{
    "first_name": "Amauri",
    "last_name": "Blanco",
    "biography": "Teste"
}

###

GET http://localhost:8080/api/users/e21f8f02-8588-4b46-8f33-2735105d8bcc

###

DELETE http://localhost:8080/api/users/e21f8f02-8588-4b46-8f33-2735105d8bcc

###

PUT http://localhost:8080/api/users/e21f8f02-8588-4b46-8f33-2735105d8bcc
Content-Type: application/json

{
    "first_name": "Elton",
    "last_name": "Blanco",
    "biography": "Updated"
}